# Generated by Django 6.0.6 on 2026-07-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("pygas_flow_rate", models.FloatField(blank=True, null=True)),
                ("biomass_flow_rate", models.FloatField(blank=True, null=True)),
                ("biomass_temperature", models.FloatField(blank=True, null=True)),
                ("reactor_gas_flow_rate", models.FloatField(blank=True, null=True)),
                ("reactor_gas_temperature", models.FloatField(blank=True, null=True)),
                ("heat_carrier_flow_rate", models.FloatField(blank=True, null=True)),
                ("heat_carrier_temperature", models.FloatField(blank=True, null=True)),
                ("product_gas_temperature", models.FloatField(blank=True, null=True)),
                (
                    "heat_carrier_return_temperature",
                    models.FloatField(blank=True, null=True),
                ),
                ("stage", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["timestamp", "id"],
                "indexes": [
                    models.Index(
                        fields=["date", "time"], name="data_app_pr_date_573837_idx"
                    ),
                    models.Index(fields=["stage"], name="data_app_pr_stage_9f38e0_idx"),
                ],
            },
        ),
    ]
